baseURL = 'https://rules.leicesterhackspace.org.uk'
languageCode = 'en-gb'
title = 'Leicester Hackspace Rules'
theme = 'leicester-hackspace-rtfm-hugo'

[params]
siteImage = "/img/hackspace-logo-inverted.svg"
siteFavIcon = "/img/hackspace-logo.svg"
siteSourceLink = "https://github.com/leicesterhackspace/leicester-hackspace-rules"

[[menus.main]]
name = 'Definitions'
pageRef = '/definitions.html'
weight = 1

[[menus.main]]
name = 'Rule 0: Do Not Be On Fire'
pageRef = '/do-not-be-on-fire.html'
weight = 10

[[menus.main]]
name = 'Rule 1: Membership'
pageRef = '/membership.html'
weight = 20

[[menus.main]]
name = 'Rule 2: Guests'
pageRef = '/guests.html'
weight = 30

[[menus.main]]
name = 'Rule 3: Respect Other Members'
pageRef = '/respect-members.html'
weight = 40

[[menus.main]]
name = 'Rule 4: Respect The Space'
pageRef = '/respect-space.html'
weight = 50

[[menus.main]]
name = 'Rule 5: Respect The Equipment'
pageRef = '/respect-equipment.html'
weight = 60

[[menus.main]]
name = 'Rule 6: Storage'
pageRef = '/storage.html'
weight = 70

[[menus.main]]
name = 'Rule 7: Donations and Loans'
pageRef = '/donations.html'
weight = 80

[[menus.main]]
name = 'Appendix A: Anti Discrimination Policy'
pageRef = '/anti-discrimination.html'
weight = 90

[[menus.main]]
name = 'Appendix B: Warnings and Complaints'
pageRef = '/complaints-warnings.html'
weight = 100

[[menus.main]]
name = 'Appendix C: GDPR and Privacy'
pageRef = '/privacy.html'
weight = 110

[[menus.main]]
name = 'Appendix D: Health and Safety'
pageRef = '/health-safety.html'
weight = 120

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
